# Generated by Django 5.0.4 on 2024-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Pass', models.CharField(max_length=100)),
                ('Lim', models.IntegerField()),
                ('FA', models.CharField(max_length=100)),
            ],
        ),
    ]
