# Generated by Django 5.0.4 on 2024-04-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FA',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Lim',
            field=models.IntegerField(null=True),
        ),
    ]
