# Generated by Django 5.0.4 on 2024-04-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0002_alter_user_fa_alter_user_lim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=5000)),
                ('Datetime', models.DateTimeField()),
            ],
        ),
    ]
