# Generated by Django 5.0.4 on 2024-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0006_alter_wallet_private_key_alter_wallet_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(max_length=5000),
        ),
    ]
