# Generated by Django 5.0.4 on 2024-05-07 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0007_alter_wallet_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='kind',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
