# Generated by Django 5.0.4 on 2024-05-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0008_wallet_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coins',
        ),
    ]
