# Generated by Django 5.0.4 on 2024-05-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0009_delete_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('Coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ndyduc_wallet.wallet')),
            ],
        ),
    ]
