# Generated by Django 5.0.4 on 2024-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0011_alter_history_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
