# Generated by Django 5.0.4 on 2024-05-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0017_alter_history_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
