# Generated by Django 5.0.4 on 2024-05-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0020_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('flag', models.IntegerField()),
                ('wallet_id', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=10)),
                ('to_id', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ndyduc_wallet.user')),
            ],
        ),
    ]
