# Generated by Django 5.0.4 on 2024-05-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0021_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gained_username', models.CharField(max_length=100)),
                ('wallet_id', models.CharField(max_length=100)),
                ('wallet_kind', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ndyduc_wallet.user')),
            ],
        ),
    ]
