# Generated by Django 5.0.4 on 2024-05-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndyduc_wallet', '0022_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ndyduc_wallet.user'),
        ),
    ]
